### ISSUE TITLE
"pzfx writer" Python module

### ISSUE THREAD

**Issue by JoseCarrascoPujante** [ulido/pzfx_parser#3]
Dear Ulrich, I wonder whether you know if there exists any Python module that allows to initialize or open .pzfx files and copy-paste the information in an excel file's worksheets (or pandas dataframes created from them) directly into GraphPad datasheets (basically a pzfx writer module). I am looking for this functionality and thought you might be familiar with the state of the art, as apparently what I am looking for is exactly the opposite of what your module does. I hope you can read this inquiry and I will hear from you soon. Best regards.

**Comment by ulido** [comment]
Hi Jose! Thanks for asking! However, I'm afraid that I don't have access to the specs for Prism PZFX XML format. I wrote this package completely based on a few Prism files I had lying around, so its functionality is somewhat limited to the use case I had (extracting data tables and freeing the data from the clutches of Prism...). Writing correct PZFX XML can probably be done, but is a much more complex task. It's easier If its limited to only certain tasks such as writing tables (your use case), and if you have access to Prism (saving Prism files and then inspecting the format). Unfortunately I don't have access to Prism myself.

**Comment by JoseCarrascoPujante** [comment]
Hi Ulrich, thanks for your quick response, much appreciated.
